import fs from "fs";
import path from "path";

const SCRATCHPAD_DIR = ".claude";

/**
 * Scratchpad persists multi-agent execution state, resolved/pending issues,
 * key facts, and error logs across sessions and restarts.
 */
export class Scratchpad {
  constructor(sessionId) {
    this.sessionId = sessionId;
    this.filePath = path.join(SCRATCHPAD_DIR, `scratchpad-${sessionId}.json`);
    this.state = {
      session_id: sessionId,
      created_at: new Date().toISOString(),
      last_updated: null,
      resolved_issues: [],
      pending_issues: [],
      key_facts: {},
      agent_outputs: {},
      error_log: [],
    };
  }

  /**
   * Updates state object and writes it synchronously to disk.
   *
   * @param {Object} updates - Partial state updates to merge.
   */
  write(updates = {}) {
    this.state = {
      ...this.state,
      ...updates,
      last_updated: new Date().toISOString(),
    };
    fs.mkdirSync(SCRATCHPAD_DIR, { recursive: true });
    fs.writeFileSync(this.filePath, JSON.stringify(this.state, null, 2), "utf8");
    console.log(`[Scratchpad] Written: ${this.filePath}`);
  }

  /**
   * Reads existing scratchpad state from disk if present.
   *
   * @returns {Object|null} The parsed state object or null if file does not exist.
   */
  read() {
    try {
      const content = fs.readFileSync(this.filePath, "utf8");
      this.state = JSON.parse(content);
      return this.state;
    } catch {
      return null; // No prior scratchpad — fresh session
    }
  }

  /**
   * Checks if scratchpad file exists on disk.
   *
   * @returns {boolean} True if file exists.
   */
  exists() {
    return fs.existsSync(this.filePath);
  }

  /**
   * Logs a resolved issue to state and persists to disk.
   *
   * @param {string} issue - Description of resolved issue.
   */
  addResolvedIssue(issue) {
    this.state.resolved_issues.push({
      issue,
      resolved_at: new Date().toISOString(),
    });
    this.write({});
  }

  /**
   * Logs a pending issue to state and persists to disk.
   *
   * @param {string} issue - Description of pending issue.
   */
  addPendingIssue(issue) {
    this.state.pending_issues.push(issue);
    this.write({});
  }

  /**
   * Sets specialist agent output in state and persists to disk.
   *
   * @param {string} agentName - Name of the agent.
   * @param {string|Object} output - Output generated by the agent.
   */
  setAgentOutput(agentName, output) {
    this.state.agent_outputs[agentName] = output;
    this.write({});
  }

  /**
   * Logs an execution error to state and persists to disk.
   *
   * @param {string} agentName - Name of the agent where error occurred.
   * @param {Error|string} error - Error object or message string.
   */
  logError(agentName, error) {
    this.state.error_log.push({
      agent: agentName,
      error: error?.message || error,
      timestamp: new Date().toISOString(),
    });
    this.write({});
  }

  /**
   * Formats scratchpad state into a resumption context string for prompt injection.
   *
   * @returns {string|null} Formatted resumption context string or null if uninitialized.
   */
  toResumptionContext() {
    if (!this.state.last_updated) return null;
    return `## RESUMING PRIOR SESSION
Session ID: ${this.state.session_id}
Last updated: ${this.state.last_updated}
Resolved: ${this.state.resolved_issues.map((r) => r.issue).join(", ") || "none"}
Pending: ${this.state.pending_issues.join(", ") || "none"}
Key facts from prior session:
${JSON.stringify(this.state.key_facts, null, 2)}`;
  }
}
